language: python

python:
  - 2.7

notifications:
  email: false

sudo: required

dist: trusty

services:
  - docker

script:
  - docker build -t --build-arg TRAVIS_BRANCH="$TRAVIS_BRANCH" neurodata .
