language: python

python:
  - 2.7

os: linux

notifications:
  email: false

sudo: required

dist: trusty

cache:
  - pip
  - apt

addons:
  apt:
     packages:
       - nginx
       - supervisor
       - python-dev
       - liblapack-dev
       - libmemcached-dev
       - memcached
       - g++
       - libxslt1-dev
       - libhdf5-serial-dev
       - libjpeg-dev
       - mysql-server-5.6
       - mysql-client-core-5.6
       - mysql-client-5.6
       - libmysqlclient-dev
       - python-numpy
       - rabbitmq-server

services:
  - mysql
  - memcached
  - rabbitmq
  - supervisor
  - nginx
  - redis

before_install:
  - sudo apt-get install build-essential checkinstall
  - sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
  - cd /usr/src
  - wget https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
  - tar xzf Python-2.7.10.tgz
  - cd Python-2.7.10
  - sudo ./configure
  - sudo make altinstall
  - sudo mkdir /var/log/neurodata
  - sudo touch /var/log/neurodata/nd.log
  - sudo chown -R www-data:www-data /var/log/neurodata
  - sudo chmod -R 777 /var/log/neurodata/

install:
  - source /home/travis/virtualenv/python2.7.10/bin/activate
  - pip2 install --upgrade ndg-httpsclient
  # - sudo apt-get -y install uwsgi uwsgi-plugin-python
  - pip2 install cython numpy
  - pip2 install -r ./setup/requirements1.txt
  - pip2 install -r ./setup/requirements.txt
  - sudo pip2 install uwsgi
  - sudo apt-get -y install uwsgi uwsgi-plugin-python
  - pip2 install uwsgi
  # 'Hacky' solution
  #- sudo mkdir /etc/uwsgi/
  #- sudo mkdir /etc/uwsgi/apps-available
  #- sudo mkdir /etc/uwsgi/apps-enabled
  - pip2 --version
  - python --version
  - pip2 freeze
  - python -c "import sys; print sys.path"
    # compiling the ctypes lib
  - make -f /home/travis/build/neurodata/ndstore/ndlib/c_version/makefile_LINUX -C ./ndlib/c_version/
    # creating the mysql user
  - mysql -u root -i -e "create user 'neurodata'@'localhost' identified by 'neur0data';" && mysql -u root -i -e "grant all privileges on *.* to 'neurodata'@'localhost' with grant option;" && mysql -u neurodata -pneur0data -i -e "CREATE DATABASE neurodjango;"
    # settings and secret_settings
  - cp ./django/ND/settings.py.example ./django/ND/settings.py
  - ln -s /home/travis/build/neurodata/ndstore/setup/docker_config/django/docker_settings_secret.py /home/travis/build/neurodata/ndstore/django/ND/settings_secret.py
    # django migrate
  - python ./django/manage.py migrate
  - echo "from django.contrib.auth.models import User; User.objects.create_superuser('neurodata', 'abc@xyz.com', 'neur0data')" | python ./django/manage.py shell
  - python ./django/manage.py collectstatic --noinput
    # move the nginx config files and start service
  - sudo rm /etc/nginx/sites-enabled/default
  - sudo rm /etc/nginx/sites-available/default
  - sudo cp ./setup/docker_config/nginx/ndstore.conf /etc/nginx/sites-available/default
  - sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
  #- sudo rm /etc/nginx/nginx.conf
  #- sudo ln -s ./setup/docker_config/nginx/nginx.conf /etc/nginx/nginx.conf
    # move uwsgi config files and start service
  - sudo chown -R www-data:www-data /tmp/
  - sudo cp ./setup/travis_config/uwsgi/ndstore.ini /etc/uwsgi/apps-available/ndstore.ini
  - sudo ln -s /etc/uwsgi/apps-available/ndstore.ini /etc/uwsgi/apps-enabled/ndstore.ini
    # move celery config files and start service
  - sudo cp ./setup/docker_config/celery/propagate.conf /etc/supervisor/conf.d/propagate.conf
  - sudo cp ./setup/docker_config/celery/ingest.conf /etc/supervisor/conf.d/ingest.conf
  - ls /home/travis/
  - ls /home/travis/build
  - ls /home/
  - ls /home/travis/virtualenv/
  - ls /home/travis/virtualenv/python2.7_with_system_site_packages/
    # restarting all the services
  - sudo chown www-data:www-data /home/travis
  - sudo service nginx restart
  - sudo service uwsgi restart
  - sudo service supervisor restart
  - sudo service rabbitmq-server restart
  - sudo service memcached restart 

script:
  - wget localhost
  - wget localhost/nd/accounts/login
  - ls -la /tmp/
  - cd ./test/
  - py.test test_info.py
  - sudo cat /var/log/uwsgi/app/*.log
  - sudo cat /var/log/neurodata/ndstore.log
