language: python

python:
  - 2.7

os: linux

notifications:
  email: false

sudo: required

dist: trusty

cache:
  - pip
  - apt

addons:
  apt:
     packages:
       - nginx
       - supervisor
       - python-dev
       - liblapack-dev
       - libmemcached-dev
       - memcached
       - g++
       - libxslt1-dev
       - libhdf5-serial-dev
       - libjpeg-dev
       - mysql-server-5.6
       - mysql-client-core-5.6
       - mysql-client-5.6
       - libmysqlclient-dev
       - python-numpy
       - rabbitmq-server
       - libssl-dev

services:
  - mysql
  - memcached
  - rabbitmq
  - supervisor
  - nginx
  - redis

install:
  - git clone -b microns https://github.com/neurodata/ndstore.git 
  - ls
  - ls setup

script:
  - setup/ndstore_install.sh
  - pip freeze
  - wget localhost
  - wget localhost/nd/accounts/login
  - ls -la /tmp/
  - cd /home/travis/build/neurodata/ndstore/test/
  - py.test test_info.py
  - sudo cat /var/log/uwsgi/app/*.log
  - sudo cat /var/log/neurodata/ndstore.log
