language: python

python:
  - 2.7

notifications:
  email: false

sudo: required

dist: trusty

services:
  - docker

script:
  - echo "Branch $TRAVIS_BRANCH"
  - docker build --build-arg BRANCH=$TRAVIS_BRANCH -t neurodata .
